require:
  - beet.contrib.messages
  - mecha.contrib.messages
  - mecha.contrib.relative_location
  - beet.contrib.auto_yaml
  - allay
  - src.plugins.misc.globals
  - src.plugins.misc.gen_namespace
  - beet.contrib.inline_function
  - beet.contrib.inline_function_tag
  - beet.contrib.template_context
  - beet.contrib.dundervar
  - lectern.contrib.relative_location
  - lectern.contrib.yaml_to_json
  - lectern.contrib.plugin
  - beet.contrib.dbg

pipeline:
  - lectern
  - src.plugins.advancements
  - beet.contrib.render
  - beet.contrib.hangman
  - mecha
  - src.plugins.misc.function_headers
  # - beet.contrib.yellow_shulker_box
  - require:
      - lectern.contrib.plugin
    pipeline:
      - lectern
    meta:
      lectern:
        load: ["test/*.md"]

meta:
  allay:
    templates:
      pretty_name: '{storage="rx:info", nbt="playerdb.pretty_name", interpret}'
    patterns:
      normal: (gray)
      error: (#CE4257)
      success: (#1DF368)
      emphasis: (gold)

  lectern:
    load: ["src/**/*.md"]

  hangman:
    match: ["*"]

  render:
    data_pack:
      functions: ["*"]
      loot_tables: ["*"]
      item_modifiers: ["*"]
      advancements: ["*"]

  format_json:
    indent: 2

  globals:
    colors:
      - '#dd9b14'
      - '#eb6f07'

  lantern_load:
    url: https://github.com/rx-modules/PlayerDB/releases

  advancements:
    item: minecraft:jukebox

  mecha:
    version: 1.18
