require:
  - src.plugins.misc.globals
  - src.plugins.misc.gen_namespace
  - beet.contrib.inline_function
  - beet.contrib.inline_function_tag
  - beet.contrib.template_context
  - beet.contrib.dundervar
  - lectern.contrib.relative_location
  - lectern.contrib.yaml_to_json
  - lectern.contrib.plugin

pipeline:
  - lectern
  - beet.contrib.auto_yaml
  - src.plugins.advancements
  - src.plugins.debug_extension
  - beet.contrib.render
  - beet.contrib.hangman
  - beet.contrib.relative_function_path
  - src.plugins.misc.function_headers
  - beet.contrib.yellow_shulker_box

meta:
  lectern:
    load: ["src/*.md", "test/*.md"]

  hangman:
    match: ["*"]

  render:
    data_pack:
      functions: ["*"]
      loot_tables: ["*"]
      item_modifiers: ["*"]

  format_json:
    indent: 2

  globals:
    colors:
      - '#dd9b14'
      - '#eb6f07'

  lantern_load:
    url: https://github.com/rx-modules/PlayerDB/releases

  advancements:
    item: minecraft:jukebox

  out_statement:

